# uncompyle6 version 3.9.0
# Python bytecode version base 2.7 (62211)
# Decompiled from: Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)]
# Embedded file name: toontown.building.FADoorCodes
# Compiled at: 2014-04-30 09:53:54
from toontown.toonbase import TTLocalizer
UNLOCKED = 0
TALK_TO_TOM = 1
DEFEAT_FLUNKY_HQ = 2
TALK_TO_HQ = 3
WRONG_DOOR_HQ = 4
GO_TO_PLAYGROUND = 5
DEFEAT_FLUNKY_TOM = 6
TALK_TO_HQ_TOM = 7
SUIT_APPROACHING = 8
BUILDING_TAKEOVER = 9
SB_DISGUISE_INCOMPLETE = 10
CB_DISGUISE_INCOMPLETE = 11
LB_DISGUISE_INCOMPLETE = 12
BB_DISGUISE_INCOMPLETE = 13
HB_DISGUISE_INCOMPLETE = 14
reasonDict = {UNLOCKED: TTLocalizer.FADoorCodes_UNLOCKED, TALK_TO_TOM: TTLocalizer.FADoorCodes_TALK_TO_TOM, 
   DEFEAT_FLUNKY_HQ: TTLocalizer.FADoorCodes_DEFEAT_FLUNKY_HQ, 
   TALK_TO_HQ: TTLocalizer.FADoorCodes_TALK_TO_HQ, 
   WRONG_DOOR_HQ: TTLocalizer.FADoorCodes_WRONG_DOOR_HQ, 
   GO_TO_PLAYGROUND: TTLocalizer.FADoorCodes_GO_TO_PLAYGROUND, 
   DEFEAT_FLUNKY_TOM: TTLocalizer.FADoorCodes_DEFEAT_FLUNKY_TOM, 
   TALK_TO_HQ_TOM: TTLocalizer.FADoorCodes_TALK_TO_HQ_TOM, 
   SUIT_APPROACHING: TTLocalizer.FADoorCodes_SUIT_APPROACHING, 
   BUILDING_TAKEOVER: TTLocalizer.FADoorCodes_BUILDING_TAKEOVER, 
   SB_DISGUISE_INCOMPLETE: TTLocalizer.FADoorCodes_SB_DISGUISE_INCOMPLETE, 
   CB_DISGUISE_INCOMPLETE: TTLocalizer.FADoorCodes_CB_DISGUISE_INCOMPLETE, 
   LB_DISGUISE_INCOMPLETE: TTLocalizer.FADoorCodes_LB_DISGUISE_INCOMPLETE, 
   BB_DISGUISE_INCOMPLETE: TTLocalizer.FADoorCodes_BB_DISGUISE_INCOMPLETE, 
   HB_DISGUISE_INCOMPLETE: TTLocalizer.FADoorCodes_HB_DISGUISE_INCOMPLETE}