# uncompyle6 version 3.9.0
# Python bytecode version base 2.7 (62211)
# Decompiled from: Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)]
# Embedded file name: toontown.reborn.DistributedPrologueEvent
# Compiled at: 2014-04-30 09:53:54
from pandac.PandaModules import *
from direct.gui.DirectGui import *
from direct.gui.OnscreenText import OnscreenText
from direct.distributed.ClockDelta import *
from direct.interval.IntervalGlobal import *
from direct.distributed.DistributedObject import DistributedObject
from direct.fsm.FSM import FSM
from toontown.toonbase import ToontownGlobals
from direct.directnotify import DirectNotifyGlobal

class DistributedPrologueEvent(DistributedObject, FSM):
    notify = DirectNotifyGlobal.directNotify.newCategory('DistributedPrologueEvent')

    def __init__(self, cr):
        DistributedObject.__init__(self, cr)
        FSM.__init__(self, 'PrologueEventFSM')
        self.cr.prologueEvent = self
        cm = CardMaker('card')
        cm.setFrameFullscreenQuad()
        self.explosionCard = render2d.attachNewNode(cm.generate())
        self.explosionCard.setTransparency(1)
        self.explosionCard.setColorScale(0, 0, 0, 0)
        self.title = OnscreenText(text='13 years ago...', pos=(0, 0), scale=0.15, font=ToontownGlobals.getSignFont(), fg=(1,
                                                                                                                          1,
                                                                                                                          1,
                                                                                                                          1), shadow=(0.1,
                                                                                                                                      0.1,
                                                                                                                                      0.1,
                                                                                                                                      1))
        self.title.setColorScale(1, 1, 1, 0)
        self.laffMeter = base.localAvatar.laffMeter
        self.book = base.localAvatar.book.bookOpenButton
        self.book2 = base.localAvatar.book.bookCloseButton
        self.eventMusic = base.loadMusic('phase_8/audio/bgm/SB_hub.ogg')

    def enterOff(self, offset):
        pass

    def exitOff(self):
        pass

    def __cleanupNPCs(self):
        pass

    def delete(self):
        self.demand('Off', 0.0)
        self.ignore('entercnode')
        self.__cleanupNPCs()
        DistributedObject.delete(self)

    def enterIdle(self, offset):
        pass

    def exitIdle(self):
        pass

    def enterEvent(self, offset):
        base.cr.playGame.hood.loader.music.stop()
        base.localAvatar.disableSleeping()
        base.localAvatar.invPage.ignoreOnscreenHooks()
        base.localAvatar.questPage.ignoreOnscreenHooks()
        self.eventInterval = Sequence(Func(base.localAvatar.disableAvatarControls), Func(base.camera.wrtReparentTo, render), Func(base.localAvatar.stopUpdateSmartCamera), Func(base.localAvatar.shutdownSmartCamera), Func(NodePath(self.book).hide), Func(NodePath(self.laffMeter).hide), Func(self.explosionCard.setColorScale, 0, 0, 0, 1), base.camera.posHprInterval(0.01, (-143.552,
                                                                                                                                                                                                                                                                                                                                                                                  -187.884,
                                                                                                                                                                                                                                                                                                                                                                                  99), (-36.435,
                                                                                                                                                                                                                                                                                                                                                                                        -10,
                                                                                                                                                                                                                                                                                                                                                                                        0), blendType='noBlend'), self.title.colorScaleInterval(2, (1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    1)), Wait(3), self.title.colorScaleInterval(2, (1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    0)), Func(base.playMusic, self.eventMusic, looping=1, volume=1.2), self.explosionCard.colorScaleInterval(2, (1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0)), base.camera.posHprInterval(7, (115.847,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     -160.519,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     99), (40.188,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           -10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           0), blendType='noBlend'), base.camera.posHprInterval(7, (115.847,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    192.455,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    99), (146.539,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          -10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          0), blendType='noBlend'), base.camera.posHprInterval(7, (-190.8777,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   137.415,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   99), (228.823,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         -10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         0), blendType='noBlend'), base.camera.posHprInterval(7, (-190.877,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  30), (270,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        0), blendType='easeInOut'), Wait(1.269), base.camera.posHprInterval(5, (-42.69,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                21), (270,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0), blendType='easeInOut'), Func(base.localAvatar.displayTalk, "Ah, what a sunny day outside! Mayhaps I should go and see th' event ov'r in Toontown Central... what was it again?"), Wait(6), Func(base.localAvatar.displayTalk, "The elections? Bah! I have better things t' do!"), Wait(5), Func(base.localAvatar.displayTalk, "Perhaps I should see what Gyro's bin workin' on. I invested in his experiments, after all."), Wait(6), Func(base.localAvatar.attachCamera), Func(base.localAvatar.initializeSmartCamera), Func(base.localAvatar.startUpdateSmartCamera), Func(base.localAvatar.enableAvatarControls))
        self.eventInterval.start()
        self.eventInterval.setT(offset)

    def exitEvent(self):
        self.eventInterval.finish()

    def enterEventTwo(self, offset):
        pass

    def exitEventTwo(self):
        pass

    def setState(self, state, timestamp):
        self.request(state, globalClockDelta.localElapsedTime(timestamp))