# uncompyle6 version 3.9.0
# Python bytecode version base 2.7 (62211)
# Decompiled from: Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)]
# Embedded file name: toontown.coghq.CashbotMintBoilerRoom_Battle00_Cogs
# Compiled at: 2014-04-30 09:53:54
from SpecImports import *
from toontown.toonbase import ToontownGlobals
CogParent = 10000
LowerCogParent = 10003
BattleParent = 10002
LowerBattleParent = 10005
FrontCogParent = 10013
CenterCogParent = 10040
BattleCellId = 0
LowerBattleCellId = 1
FrontBattleCellId = 2
CenterBattleCellId = 3
BattleCells = {BattleCellId: {'parentEntId': BattleParent, 'pos': Point3(0, 0, 0)}, 
   LowerBattleCellId: {'parentEntId': LowerBattleParent, 'pos': Point3(0, 0, 0)}, 
   FrontBattleCellId: {'parentEntId': FrontCogParent, 'pos': Point3(0, 0, 0)}, 
   CenterBattleCellId: {'parentEntId': CenterCogParent, 'pos': Point3(0, 0, 0)}}
CogData = [
 {'parentEntId': CogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintSkelecogLevel, 
    'battleCell': BattleCellId, 
    'pos': Point3(-6, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 1},
 {'parentEntId': CogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintSkelecogLevel, 
    'battleCell': BattleCellId, 
    'pos': Point3(-2, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 1},
 {'parentEntId': CogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintSkelecogLevel, 
    'battleCell': BattleCellId, 
    'pos': Point3(2, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 1},
 {'parentEntId': CogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintSkelecogLevel, 
    'battleCell': BattleCellId, 
    'pos': Point3(6, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 1},
 {'parentEntId': LowerCogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintCogLevel, 
    'battleCell': LowerBattleCellId, 
    'pos': Point3(-6, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 0},
 {'parentEntId': LowerCogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintSkelecogLevel, 
    'battleCell': LowerBattleCellId, 
    'pos': Point3(-2, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 1},
 {'parentEntId': LowerCogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintSkelecogLevel, 
    'battleCell': LowerBattleCellId, 
    'pos': Point3(2, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 1},
 {'parentEntId': LowerCogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintCogLevel, 
    'battleCell': LowerBattleCellId, 
    'pos': Point3(6, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 0},
 {'parentEntId': FrontCogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintCogLevel, 
    'battleCell': FrontBattleCellId, 
    'pos': Point3(-6, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 0},
 {'parentEntId': FrontCogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintCogLevel, 
    'battleCell': FrontBattleCellId, 
    'pos': Point3(-2, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 0},
 {'parentEntId': FrontCogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintCogLevel, 
    'battleCell': FrontBattleCellId, 
    'pos': Point3(2, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 0},
 {'parentEntId': FrontCogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintCogLevel, 
    'battleCell': FrontBattleCellId, 
    'pos': Point3(6, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 0},
 {'parentEntId': CenterCogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintCogLevel, 
    'battleCell': CenterBattleCellId, 
    'pos': Point3(-6, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 0},
 {'parentEntId': CenterCogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintSkelecogLevel, 
    'battleCell': CenterBattleCellId, 
    'pos': Point3(-2, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 1},
 {'parentEntId': CenterCogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintSkelecogLevel, 
    'battleCell': CenterBattleCellId, 
    'pos': Point3(2, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 1},
 {'parentEntId': CenterCogParent, 'boss': 0, 
    'level': ToontownGlobals.CashbotMintCogLevel, 
    'battleCell': CenterBattleCellId, 
    'pos': Point3(6, 0, 0), 
    'h': 180, 
    'behavior': 'stand', 
    'path': None, 
    'skeleton': 0}]
ReserveCogData = []